CREATE TABLE REFUGEE(
REFUGEE_ID NUMBER(7) CONSTRAINT REF_PK PRIMARY KEY,
FIRST_NAME VARCHAR2(50) NOT NULL,
LAST_NAME VARCHAR2(50),
DATE_OF_BIRTH DATE,
GENDER VARCHAR2(6) NOT NULL,
BLOODGROUP VARCHAR2(3) NOT NULL,
COUNTRY_OF_ORIGIN VARCHAR2(50) NOT NULL,
PASSPORT_NO VARCHAR2(20),
ETHNIC_TRIBAL_SECTARIAN_GROUP VARCHAR2(50),
RELIGION VARCHAR2(50),
FATHER_ID NUMBER(7),
MOTHER_ID NUMBER(7),
SPOUSE_ID NUMBER(7),
LEGALGUARDIAN_ID NUMBER(7),
CONSTRAINT FATHER_FK FOREIGN KEY(FATHER_ID) REFERENCES REFUGEE(REFUGEE_ID) ON delete set null, 
CONSTRAINT MOTHER_FK FOREIGN KEY(MOTHER_ID) REFERENCES REFUGEE(REFUGEE_ID) on delete set null, 
CONSTRAINT SPOUSE_FK FOREIGN KEY(SPOUSE_ID) REFERENCES REFUGEE(REFUGEE_ID) on delete set null, 
CONSTRAINT LEGAL_FK FOREIGN KEY(LEGALGUARDIAN_ID) REFERENCES REFUGEE(REFUGEE_ID) on delete set null,
IMAGE_PATH VARCHAR2(200)
);

CREATE SEQUENCE REFUGEE_SEQ
INCREMENT BY 1
START WITH 1000000
MAXVALUE 1099999
NOCYCLE;



CREATE TABLE LOCATION(
LOCATION_ID NUMBER(7) CONSTRAINT LOC_PK PRIMARY KEY,
CITY VARCHAR2(50) NOT NULL,
STATE VARCHAR2(50),
COUNTRY VARCHAR2(50) NOT NULL
);

CREATE SEQUENCE LOCATION_SEQ
INCREMENT BY 1
START WITH 5000000
MAXVALUE 5199999
NOCYCLE;

CREATE TABLE INSTITUTE(
INSTITUTE_ID NUMBER(7) CONSTRAINT INS_PK PRIMARY KEY,
INSTITUTE_NAME VARCHAR2(100) NOT NULL,
LOCATION_ID NUMBER(7) NOT NULL, 
CONSTRAINT LOC_FK FOREIGN KEY(LOCATION_ID) REFERENCES LOCATION(LOCATION_ID)
);

CREATE SEQUENCE INSTITUTE_SEQ
INCREMENT BY 1
START WITH 6000000
MAXVALUE 6299999
NOCYCLE;

CREATE TABLE DOCTOR_NURSE_OFFICER(
DOCTOR_NURSE_OFFICER_ID NUMBER(7) CONSTRAINT DNO_PK PRIMARY KEY,
DOCTOR_NURSE_OFFICER_FIRSTNAME VARCHAR2(50) NOT NULL,
DOCTOR_NURSE_OFFICER_LASTNAME VARCHAR2(50),
SPECIALIZATION VARCHAR2(100) NOT NULL,
DOCIMAGE VARCHAR2(200)
);

CREATE SEQUENCE DOCTOR_NURSE_OFFICER_SEQ
INCREMENT BY 1
START WITH 3000000
MAXVALUE 3074999
NOCYCLE;

CREATE TABLE VOLUNTEER(
VOLUNTEER_ID NUMBER(7) CONSTRAINT VOL_PK PRIMARY KEY,
VOLUNTEER_FIRSTNAME VARCHAR2(50) NOT NULL,
VOLUNTEER_LASTNAME VARCHAR2(50)
);

CREATE SEQUENCE VOLUNTEER_SEQ
INCREMENT BY 1
START WITH 2000000
MAXVALUE 2024999
NOCYCLE;

CREATE TABLE EDUCATIONAL_OCCUPATIONAL_INFO(
REFUGEE_ID NUMBER(7),
INSTITUTE_ID NUMBER(7),
ENDYEAR NUMBER(4),
DEGREE VARCHAR2(100),
OCCUPATION VARCHAR2(50) NOT NULL,
CONSTRAINT EO_PK PRIMARY KEY(REFUGEE_ID,INSTITUTE_ID),
CONSTRAINT REF_FK FOREIGN KEY(REFUGEE_ID) REFERENCES REFUGEE(REFUGEE_ID) ON DELETE CASCADE,
CONSTRAINT INS_FK FOREIGN KEY(INSTITUTE_ID) REFERENCES INSTITUTE(INSTITUTE_ID),
SPECIALIZATION VARCHAR2(100)
);

CREATE TABLE PRESCRIPTION(
PRESCRIPTION_SERIAL NUMBER (7) CONSTRAINT PRES_PK PRIMARY KEY,
REFUGEE_ID NUMBER(7) NOT NULL,
DOCTOR_NURSE_OFFICER_ID NUMBER(7) NOT NULL,
CONSTRAINT REFCHECKUP_FK FOREIGN KEY(REFUGEE_ID) REFERENCES REFUGEE(REFUGEE_ID) on delete cascade,
CONSTRAINT DNO_FK FOREIGN KEY(DOCTOR_NURSE_OFFICER_ID) REFERENCES DOCTOR_NURSE_OFFICER(DOCTOR_NURSE_OFFICER_ID) on delete cascade
);

CREATE SEQUENCE PRESCRIPTION_SEQ
INCREMENT BY 1
START WITH 7000000
MAXVALUE 7499999
NOCYCLE;



CREATE TABLE DIAGNOSIS(
DIAGNOSIS_ID NUMBER(8)  CONSTRAINT DIAG_PK PRIMARY KEY,
PRESCRIPTION_SERIAL NUMBER (7) NOT NULL,
CONSTRAINT DIAG_FK FOREIGN KEY(PRESCRIPTION_SERIAL) REFERENCES PRESCRIPTION(PRESCRIPTION_SERIAL) on delete cascade,
DIAGNOSIS_NAME VARCHAR2(50) NOT NULL,
MEDICINE_NAME VARCHAR2(100)
);

CREATE SEQUENCE DIAGNOSIS_SEQ
INCREMENT BY 1
START WITH 80000000
MAXVALUE 80999999
NOCYCLE;


CREATE TABLE COMPLAINT(
COMPLAINT_SERIAL_NUMBER NUMBER(8) CONSTRAINT COM_PK PRIMARY KEY,
MISDEED VARCHAR2(50) NOT NULL,
COMPLAINT_BY_REFUGEE NUMBER(7),
COMPLAINT_BY_VOLUNTEER NUMBER(7),
COMPLAINT_AGAINST NUMBER(7) NOT NULL,
CONSTRAINT COMAG_FK FOREIGN KEY(COMPLAINT_AGAINST) REFERENCES REFUGEE(REFUGEE_ID) on delete cascade,
CONSTRAINT COMBYREF_FK FOREIGN KEY(COMPLAINT_BY_REFUGEE) REFERENCES REFUGEE(REFUGEE_ID) on delete cascade,
CONSTRAINT COMBYVOL_FK FOREIGN KEY(COMPLAINT_BY_VOLUNTEER) REFERENCES VOLUNTEER(VOLUNTEER_ID) on delete cascade
);

CREATE SEQUENCE COMPLAINT_SERIAL_SEQ
INCREMENT BY 1
START WITH 10000000
MAXVALUE 10999999
NOCYCLE;

CREATE TABLE PASS(
DOCTOR_NURSE_OFFICER_ID NUMBER(7) CONSTRAINT PASS_PK PRIMARY KEY,
CONSTRAINT PASS_FK FOREIGN KEY(DOCTOR_NURSE_OFFICER_ID) REFERENCES DOCTOR_NURSE_OFFICER(DOCTOR_NURSE_OFFICER_ID) on delete cascade,
PASSWORD VARCHAR2(50) NOT NULL
);

CREATE TABLE INSCOUNT(
  INSTITUTE_ID NUMBER(7) CONSTRAINT INSCOUNT_PK PRIMARY KEY,
  CONSTRAINT INSCOUNT_FK FOREIGN KEY(INSTITUTE_ID) REFERENCES INSTITUTE(INSTITUTE_ID) ON DELETE CASCADE,
  TOTAL_REFUGEE NUMBER NOT NULL
);

CREATE TABLE LOCATIONCOUNT(
LOCATION_ID NUMBER(7) CONSTRAINT LOCCOUNT_PK PRIMARY KEY,
COUNTLOC NUMBER NOT NULL,
CONSTRAINT LOCCOUNT_FK FOREIGN KEY(LOCATION_ID) REFERENCES LOCATION(LOCATION_ID) ON DELETE CASCADE
);